### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ggarza31416** [schonz/mediabackup#1]
there's is a typo in line 298 ---> ":=", please verify

**Comment by schonz** [comment]
Hey @ggarza31416 , thanks reaching out.

I believe you're talking about Line #298 in "mediabackup-agent.py".
This is actually called the "_Walrus Operator_" which released in Python3.8. The docs show some examples of how this new operator can be used. It's a nice way to cleanup code by performing 2 commands at the same time. 

In this specific example (`while chunk := reader.read(chunk_size):`) I'm assigning the value of `reader.read(chunk_size)` to the variable `chunk` **and** checking if `reader.read(chunk_size)` is returning null at the same time. The alternative is I would have to assign  `chunk = reader.read(chunk_size)` and then perform `while chunk:`.

Hope that helps

Docs about the walrus operator: 
https://docs.python.org/3/whatsnew/3.8.html
